/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import  { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Rafael(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Rafael.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions["Typing"].reset().play().fadeIn(0.5);
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Baseline">
          <skinnedMesh
            name="Rafael"
            geometry={nodes.Rafael.geometry}
            material={materials.All}
            skeleton={nodes.Rafael.skeleton}
          />
          <primitive object={nodes.Hips} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Rafael.glb')
